# Generated by Django 3.1.7 on 2021-03-15 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=32)),
                ('building_number', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=36)),
                ('country', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(max_length=150)),
                ('nip_number', models.CharField(max_length=10)),
                ('print_number', models.PositiveIntegerField()),
                ('date_printed', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('receipt_number', models.PositiveIntegerField()),
                ('checkout_number', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_nip', models.CharField(blank=True, max_length=10, null=True)),
                ('company_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.address')),
                ('sales_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='booking.address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_type', models.CharField(max_length=1)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='booking.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('nip_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('company_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='booking.address')),
            ],
        ),
    ]
