# Generated by Django 3.1.7 on 2021-03-17 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=32)),
                ('building_number', models.CharField(max_length=10)),
                ('post_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=36)),
                ('country', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('nip_number', models.CharField(max_length=10)),
                ('company_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='booking.address')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_nip', models.CharField(blank=True, max_length=10, null=True)),
                ('buyer_pesel', models.CharField(blank=True, max_length=11, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_finished', models.DateField()),
                ('invoice_number', models.CharField(editable=False, max_length=20)),
                ('buyer_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.address')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.company')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('header', models.CharField(blank=True, max_length=50, null=True)),
                ('print_number', models.PositiveIntegerField(editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.CharField(max_length=10)),
                ('receipt_number', models.PositiveIntegerField(editable=False)),
                ('checkout_number', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_nip', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.company')),
                ('sales_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='booking.address')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_type', models.CharField(max_length=1)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='booking.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=15)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_value', models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_tax', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.invoice')),
            ],
        ),
    ]
