# Generated by Django 3.1.7 on 2021-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_discount',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='checkout_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
