# Generated by Django 3.1.7 on 2021-03-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_receipt_nip_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='company_address',
        ),
    ]
