# Generated by Django 3.1.7 on 2021-03-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210315_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='number',
            new_name='receipt_number',
        ),
    ]
