# Generated by Django 3.1.7 on 2021-03-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210317_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='seller',
            new_name='company',
        ),
    ]
