# Generated by Django 3.1.7 on 2021-03-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210317_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_finished',
            field=models.DateTimeField(),
        ),
    ]
