# Generated by Django 3.1.7 on 2021-03-16 12:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('booking', '0006_delete_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ReceiptProduct',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('pesel_number', models.CharField(max_length=11)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.address')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('date_created', models.DateField()),
                ('date_finished', models.DateField()),
                ('invoice_number', models.CharField(max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.company')),
            ],
        ),
    ]
