# Generated by Django 3.1.7 on 2021-03-16 12:12

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210316_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=15)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_value', models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_tax', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pesel_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
