# Generated by Django 3.1.7 on 2021-03-17 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210317_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_prepayment_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='previous_prepayment',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='vat_tax',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='InvoicePrepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_tax', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayment_invoices', to='booking.invoice')),
            ],
        ),
    ]
