# Generated by Django 3.1.7 on 2021-03-18 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210317_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceprepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayments', to='booking.invoice'),
        ),
    ]
