# Generated by Django 3.1.7 on 2021-03-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210318_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='is_prepayment_invoice',
            new_name='is_prepayment',
        ),
    ]
